os:
  - linux
  - osx

arch:
  - amd64
  - arm64

sudo: false

language: node_js

node_js:
  - node
  - lts/*
  - lts/dubnium
  - lts/carbon
  - lts/boron
  - lts/argon

install:
  - . ./scripts/travisci/install.sh

script:
  - . ./scripts/travisci/test.sh

cache:
  directories:
    - 'node_modules'

after_success:
  - npm run report-coverage
