os:
  - linux
  - osx

arch:
  - amd64
  - arm64

sudo: false

language: cpp

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
env:
  matrix:
    - TRAVIS_NODE_VERSION="node"
    - TRAVIS_NODE_VERSION="lts/*"
    - TRAVIS_NODE_VERSION="lts/argon"
    - TRAVIS_NODE_VERSION="lts/boron"
    - TRAVIS_NODE_VERSION="lts/carbon"
    - TRAVIS_NODE_VERSION="lts/dubnium"
    - TRAVIS_NODE_VERSION="lts/erbium"

before_install:
  - . ./scripts/travisci/prepare.sh

install:
  - . ./scripts/travisci/install.sh

script:
  - . ./scripts/travisci/test.sh

cache:
  directories:
    - 'node_modules'

after_success:
  - npm run report-coverage
