os:
  - linux
  - osx

arch:
  - amd64
  - arm64

addons:
  apt:
    packages:
      - tcpdump

language: node_js

node_js:
  - lts/argon
  - lts/boron
  - lts/carbon
  - lts/dubnium
  - lts/*
  - node

install:
  - . ./scripts/travisci/install.sh

script:
  - sudo ./scripts/travisci/test.sh

cache:
  directories:
    - 'node_modules'

after_success:
  - npm run report-coverage
